// TODO LIST
export const ADD_TODO_ACTION = "ADD_TODO_ACTION";
export const UPDATE_TODO_ACTION = "UPDATE_TODO_ACTION";
export const DELETE_TODO_ACTION = "DELETE_TODO_ACTION";

// TODO FILTER
export const UPDATE_FILTER_ACTION = "UPDATE_FILTER_ACTION";
